### ISSUE TITLE
Cannot reference cost('shipping') before it is assigned

### ISSUE THREAD

**Issue by murwiz** [interchange/Interchange6#19]
I have a cart page which allows the customer to select the shipping mode (and thus determine shipping cost). The cart page also displays the current shipping cost, via $cart->cost('shipping') and assigning that to a context variable. However, if the "costs" structure is empty then a reference to cost('shipping') throws a fatal error (line 367).

The only way to know ahead of time if cost('shipping') is safe to call is to scan the costs array beforehand. I don't think cost('foo') should throw a fatal error, but should just return "undef".

**Comment by SysPete** [comment]
@racke/@sbatschelet  we could change the cost method to return undef rather than die - thoughts?

**Comment by SysPete** [comment]
@racke thoughts on this? I think @murwiz has a point and returning undef in this case is probably the best option.

**Comment by racke** [comment]
Yeah undef works for me.
